event entity @e[type=glc:chessmen,r=32] force_despawn
summon glc:chessmen ~1 ~0.5 ~ make_white_rook_east
summon glc:chessmen ~1 ~0.5 ~1 make_white_knight_east
summon glc:chessmen ~1 ~0.5 ~2 make_white_bishop_east
summon glc:chessmen ~1 ~0.5 ~3 make_white_queen_east
summon glc:chessmen ~1 ~0.5 ~4 make_white_king_east
summon glc:chessmen ~1 ~0.5 ~5 make_white_bishop_east
summon glc:chessmen ~1 ~0.5 ~6 make_white_knight_east
summon glc:chessmen ~1 ~0.5 ~7 make_white_rook_east
summon glc:chessmen ~2 ~0.5 ~ make_white_pawn_east
summon glc:chessmen ~2 ~0.5 ~1 make_white_pawn_east
summon glc:chessmen ~2 ~0.5 ~2 make_white_pawn_east
summon glc:chessmen ~2 ~0.5 ~3 make_white_pawn_east
summon glc:chessmen ~2 ~0.5 ~4 make_white_pawn_east
summon glc:chessmen ~2 ~0.5 ~5 make_white_pawn_east
summon glc:chessmen ~2 ~0.5 ~6 make_white_pawn_east
summon glc:chessmen ~2 ~0.5 ~7 make_white_pawn_east
summon glc:chessmen ~8 ~0.5 ~ make_black_rook_east
summon glc:chessmen ~8 ~0.5 ~1 make_black_knight_east
summon glc:chessmen ~8 ~0.5 ~2 make_black_bishop_east
summon glc:chessmen ~8 ~0.5 ~3 make_black_queen_east
summon glc:chessmen ~8 ~0.5 ~4 make_black_king_east
summon glc:chessmen ~8 ~0.5 ~5 make_black_bishop_east
summon glc:chessmen ~8 ~0.5 ~6 make_black_knight_east
summon glc:chessmen ~8 ~0.5 ~7 make_black_rook_east
summon glc:chessmen ~7 ~0.5 ~ make_black_pawn_west
summon glc:chessmen ~7 ~0.5 ~1 make_black_pawn_west
summon glc:chessmen ~7 ~0.5 ~2 make_black_pawn_west
summon glc:chessmen ~7 ~0.5 ~3 make_black_pawn_west
summon glc:chessmen ~7 ~0.5 ~4 make_black_pawn_west
summon glc:chessmen ~7 ~0.5 ~5 make_black_pawn_west
summon glc:chessmen ~7 ~0.5 ~6 make_black_pawn_west
summon glc:chessmen ~7 ~0.5 ~7 make_black_pawn_west