name: Build and upload MC Addon
on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Build mcaddon files.
              run: |
                  tmp=(*_BP)
                  zip -r "$tmp.mcaddon" "$tmp"
                  tmp2=(*_RP)
                  zip -r "$tmp2.mcaddon" "$tmp2"
                  zip "release.mcaddon" "$tmp" "$tmp2"
                  rm "$tmp1.mcaddon" "$tmp2.mcaddon"
                  
            - uses: djnicholson/release-action@v2.10
            - name: Release mcaddon
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-name: Fun & Games Addon
                  tag-name: rolling-release
                  asset-name: MC Addon File
                  file: release.mcaddon
