name: Build and upload MC Addon
on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Build mcaddon files.
              run: |
                  tmp=(*_BP)
                  zip -r "$tmp.mcaddon" "$tmp"
                  tmp2=(*_RP)
                  zip -r "$tmp2.mcaddon" "$tmp2"
                  zip "${tmp2%_RP}.mcaddon" "$tmp.mcaddon" "$tmp2.mcaddon"

            - uses: actions/upload-artifact@v2.2.2
              with:
                  name: "${tmp%_RP}.mcaddon"
                  path: ./
