name: Build and upload MC Addon
on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Build mcaddon files.
              run: |
                  tmp=(*_BP)
                  zip -r "$tmp.mcaddon" "$tmp"
                  tmp2=(*_RP)
                  zip -r "$tmp2.mcaddon" "$tmp2"
                  zip "release.mcaddon" "$tmp" "$tmp2"

              - uses: PeerXu/upload-asset@v1
                  with:
                      file: release.mcaddon
                      os: linux
                      arch: amd64
                      with_tag: true
                      with_sha1: true
                      suffix: .mcaddon
                  env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
