name: Build and upload MC Addon
on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Build mcaddon files.
              run: |
                  tmp=(*_BP)
                  zip -r "$tmp[1].mcaddon" "$tmp[1]"
                  tmp=(*_RP)
                  zip -r "$tmp[1].mcaddon" "$tmp[1]"
                  zip "${tmp%_RP}.mcaddon" "*.mcaddon"

            - uses: actions/upload-artifact@v2.2.2
              with:
                  name: "${tmp%_RP}.mcaddon"
                  path: ./
